version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql-ecommerce
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce_lp2_prod
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ecommerce_app
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce_lp2_prod?serverTimezone=America/Lima&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    name: ecommerce_net