version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql-ecommerce
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce_lp2_prod
      MYSQL_ROOT_PASSWORD: admin123
    # === OPTIMIZACIÓN DE MEMORIA PARA MAQUINAS DE 1GB DE RAM ===
    command: --innodb_buffer_pool_size=64M --innodb_log_buffer_size=16M --max_connections=50
    deploy:
      resources:
        limits:
          memory: 400M
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      timeout: 5s
      retries: 4
      start_period: 20s

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ecommerce_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce_lp2_prod?serverTimezone=America/Lima&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - backend
    volumes:
      - images_data:/app/images
    # Mantiene los 15 segundos de espera para que MySQL respire
    command: ["sh", "-c", "sleep 15 && java -jar app.jar"]

volumes:
  mysql_data:
  images_data:

networks:
  backend:
    name: ecommerce_net